# add stages here 
stages:

  get_data:
    cmd: python src/stage_01_load_save.py
    deps:
    - src/stage_01_load_save.py
    - src/utils/common.py
    - configs/config.yaml
    outs:
    - artifacts/raw_local_dir/data.csv

  split_data:
    cmd: python src/stage_02_split_data.py
    deps:
    - src/stage_02_split_data.py
    - src/utils/common.py
    - configs/config.yaml
    - artifacts/raw_local_dir/data.csv
    params:
     - base.random_state
     - base.test_size
    outs:
    - artifacts/split_data_dir/train.csv
    - artifacts/split_data_dir/test.csv

  train_data:
    cmd: python src/stage_03_train.py
    deps:
    - src/stage_03_train.py
    - src/utils/common.py
    - configs/config.yaml
    - artifacts/split_data_dir/train.csv
    params:
      - model_params.ElasticNet.alpha
      - model_params.ElasticNet.l1_ratio
    outs:
    - artifacts/model_dir/model.pkl

  evaluate:
    cmd: python src/stage_04_evaluate.py
    deps:
    - src/stage_04_evaluate.py
    - src/utils/common.py
    - configs/config.yaml
    - artifacts/split_data_dir/test.csv
    - artifacts/model_dir/model.pkl
    metrics:
      - scores.json:
          cache: false